services:
  - postgresql

before_script:
  - psql
  - CREATE DATABASE chitter_test;
  - /c chitter_test;
  - CREATE TABLE users(id SERIAL PRIMARY KEY, username VARCHAR(20), email VARCHAR(60), password VARCHAR(30));
  - CREATE TABLE peeps(id SERIAL PRIMARY KEY, content VARCHAR(240), date VARCHAR(10), time VARCHAR(5), user_id INTEGER REFERENCES users (id) ON DELETE CASCADE);
  - CREATE TABLE replies(id SERIAL PRIMARY KEY, content VARCHAR(240), date VARCHAR(10), time VARCHAR(5), user_id INTEGER REFERENCES users (id), peep_id INTEGER REFERENCES peeps (id) ON DELETE CASCADE);
script:
  - bundle exec rspec
